In [3]:
import pandas as pd
import random
import datetime

# Function to generate synthetic data
def generate_data(n):
    data = {
        'Vehicle_Model': [random.choice(['Car', 'SUV','Van' ,'Truck','Bus','Motorcycle']) for _ in range(n)],
        'Mileage': [random.randint(30000, 80000) for _ in range(n)],
        'Maintenance_History': [random.choice(['Good', 'Average', 'Poor']) for _ in range(n)],
        'Reported_Issues': [random.randint(0, 5) for _ in range(n)],
        'Need_Maintenance': [random.randint(0, 1) for _ in range(n)],
        'Vehicle_Age': [random.randint(1, 10) for _ in range(n)],
        'Fuel_Type': [random.choice(['Diesel', 'Petrol', 'Electric']) for _ in range(n)],
        'Transmission_Type': [random.choice(['Automatic', 'Manual']) for _ in range(n)],
        'Engine_Size': [random.choice([800,1000, 1500, 2000, 2500]) for _ in range(n)],
        'Odometer_Reading': [random.randint(1000, 150000) for _ in range(n)],
        'Last_Service_Date': [(datetime.datetime.now() - datetime.timedelta(days=random.randint(30, 365))).strftime('%Y-%m-%d') for _ in range(n)],
        'Warranty_Expiry_Date': [(datetime.datetime.now() + datetime.timedelta(days=random.randint(30, 365*2))).strftime('%Y-%m-%d') for _ in range(n)],
        'Owner_Type': [random.choice(['First', 'Second', 'Third']) for _ in range(n)],
        'Insurance_Premium': [random.randint(5000, 30000) for _ in range(n)],
        'Service_History': [random.randint(1, 10) for _ in range(n)],
        'Accident_History': [random.randint(0, 3) for _ in range(n)],
        'Fuel_Efficiency': [random.uniform(10, 20) for _ in range(n)],
        'Tire_Condition': [random.choice(['New', 'Good', 'Worn Out']) for _ in range(n)],
        'Brake_Condition': [random.choice(['New', 'Good', 'Worn Out']) for _ in range(n)],
        'Battery_Status': [random.choice(['New', 'Good', 'Weak']) for _ in range(n)]
    }
    return data

# Generate synthetic data
n = 50000
data = generate_data(n)

# Convert the dictionary to a DataFrame
df = pd.DataFrame(data)

# Save the DataFrame to a CSV file
df.to_csv('vehicle_maintenance_data.csv', index=False)

# Display the DataFrame
print(df.head())

  Vehicle_Model  Mileage Maintenance_History  Reported_Issues  \
0           Bus    57303                Poor                5
1         Truck    74754                Poor                2
2           Van    70021             Average                1
3           SUV    36688             Average                3
4           Bus    70756                Good                4

   Need_Maintenance  Vehicle_Age Fuel_Type Transmission_Type  Engine_Size  \
0                 0            4  Electric            Manual         2000
1                 0            3  Electric            Manual         1000
2                 1            3    Petrol            Manual         2000
3                 0            2  Electric         Automatic         1500
4                 1            2    Petrol         Automatic          800

   Odometer_Reading Last_Service_Date Warranty_Expiry_Date Owner_Type  \
0             75788        2023-06-30           2025-07-13      Third
1            122646        2023-12-09           2024-06-24     Second
2             26188        2023-04-27           2024-05-03     Second
3             78701        2023-08-17           2025-11-21     Second
4             83544        2023-07-31           2025-02-09      Third

   Insurance_Premium  Service_History  Accident_History  Fuel_Efficiency  \
0               5034                6                 3        14.735662
1              19963                2                 2        14.285425
2              26578                5                 0        14.735660
3              24536                3                 3        13.717582
4               9695                8                 2        11.196542

  Tire_Condition Brake_Condition Battery_Status
0       Worn Out            Good           Weak
1       Worn Out            Good           Good
2           Good            Good           Good
3            New        Worn Out            New
4           Good             New            New

In [4]:
df = pd.read_csv('vehicle_maintenance_data.csv')
df

,Vehicle_Model,Mileage,Maintenance_History,Reported_Issues,Need_Maintenance,Vehicle_Age,Fuel_Type,Transmission_Type,Engine_Size,Odometer_Reading,Last_Service_Date,Warranty_Expiry_Date,Owner_Type,Insurance_Premium,Service_History,Accident_History,Fuel_Efficiency,Tire_Condition,Brake_Condition,Battery_Status
0,Bus,57303,Poor,5,0,4,Electric,Manual,2000,75788,2023-06-30,2025-07-13,Third,5034,6,3,14.735662,Worn Out,Good,Weak
1,Truck,74754,Poor,2,0,3,Electric,Manual,1000,122646,2023-12-09,2024-06-24,Second,19963,2,2,14.285425,Worn Out,Good,Good
2,Van,70021,Average,1,1,3,Petrol,Manual,2000,26188,2023-04-27,2024-05-03,Second,26578,5,0,14.735660,Good,Good,Good
3,SUV,36688,Average,3,0,2,Electric,Automatic,1500,78701,2023-08-17,2025-11-21,Second,24536,3,3,13.717582,New,Worn Out,New
4,Bus,70756,Good,4,1,2,Petrol,Automatic,800,83544,2023-07-31,2025-02-09,Third,9695,8,2,11.196542,Good,New,New
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,Truck,48313,Average,3,1,9,Diesel,Automatic,2500,81354,2023-04-12,2024-06-05,Third,5425,10,0,18.003884,New,Good,Good
49996,SUV,79686,Average,5,0,1,Diesel,Automatic,1500,77113,2023-05-08,2025-11-23,Second,9028,10,0,12.722385,Good,New,Good
49997,SUV,67772,Poor,3,1,4,Petrol,Automatic,800,67118,2023-10-03,2024-12-30,First,7288,5,0,15.313674,Worn Out,Good,New
49998,SUV,33619,Poor,0,1,5,Diesel,Automatic,2500,44452,2023-10-22,2024-05-26,Third,25983,10,0,15.112470,New,Good,New
49999,Truck,31946,Average,3,0,10,Electric,Automatic,800,137688,2023-07-09,2025-01-07,Second,16172,2,2,19.697504,Good,Good,New

In [ ]:
Vehicle_Model, Maintenance_History, Reported_Issues,

In [5]:
!pip install Faker

Collecting Faker
  Obtaining dependency information for Faker from https://files.pythonhosted.org/packages/3e/ac/b070934c1f1b7a6deefe5f4cda2a6ba988277765065d658f2d7e2bbb79dd/Faker-24.4.0-py3-none-any.whl.metadata
  Downloading Faker-24.4.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: python-dateutil>=2.4 in c:\users\asus\anaconda3\lib\site-packages (from Faker) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\asus\anaconda3\lib\site-packages (from python-dateutil>=2.4->Faker) (1.16.0)
Downloading Faker-24.4.0-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
    --------------------------------------- 0.0/1.8 MB ? eta -:--:--
   - -------------------------------------- 0.1/1.8 MB 1.5 MB/s eta 0:00:02
   -- ------------------------------------- 0.1/1.8 MB 1.4 MB/s eta 0:00:02
   --- ------------------------------------ 0.1/1.8 MB 1.1 MB/s eta 0:00:02
   ---- ----------------------------------- 0.2/1.8 MB 1.0 MB/s eta 0:00:02
   ---- ----------------------------------- 0.2/1.8 MB 1.0 MB/s eta 0:00:02
   ---- ----------------------------------- 0.2/1.8 MB 1.0 MB/s eta 0:00:02
   ---- ----------------------------------- 0.2/1.8 MB 1.0 MB/s eta 0:00:02
   ------ --------------------------------- 0.3/1.8 MB 840.4 kB/s eta 0:00:02
   -------- ------------------------------- 0.4/1.8 MB 916.6 kB/s eta 0:00:02
   --------- ------------------------------ 0.4/1.8 MB 981.9 kB/s eta 0:00:02
   ----------- ---------------------------- 0.5/1.8 MB 1.0 MB/s eta 0:00:02
   ------------- -------------------------- 0.6/1.8 MB 1.1 MB/s eta 0:00:02
   --------------- ------------------------ 0.7/1.8 MB 1.1 MB/s eta 0:00:01
   --------------- ------------------------ 0.7/1.8 MB 1.1 MB/s eta 0:00:01
   ------------------ --------------------- 0.8/1.8 MB 1.2 MB/s eta 0:00:01
   --------------------- ------------------ 1.0/1.8 MB 1.3 MB/s eta 0:00:01
   ------------------------ --------------- 1.1/1.8 MB 1.4 MB/s eta 0:00:01
   ------------------------ --------------- 1.1/1.8 MB 1.4 MB/s eta 0:00:01
   -------------------------- ------------- 1.2/1.8 MB 1.4 MB/s eta 0:00:01
   -------------------------- ------------- 1.2/1.8 MB 1.4 MB/s eta 0:00:01
   ------------------------------- -------- 1.4/1.8 MB 1.5 MB/s eta 0:00:01
   --------------------------------- ------ 1.5/1.8 MB 1.5 MB/s eta 0:00:01
   ------------------------------------- -- 1.6/1.8 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------  1.7/1.8 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 1.6 MB/s eta 0:00:00
Installing collected packages: Faker
Successfully installed Faker-24.4.0

In [9]:
import pandas as pd
import random
from faker import Faker
import datetime

fake = Faker()

def generate_data_with_faker(n):
    data = {
        'Vehicle_Model': [random.choice(['Car', 'SUV', 'Van', 'Truck', 'Bus', 'Motorcycle']) for _ in range(n)],
        'Mileage': [random.randint(30000, 80000) for _ in range(n)],
        'Maintenance_History': [random.choice(['Good', 'Average', 'Poor']) for _ in range(n)],
        'Reported_Issues': [random.randint(0, 5) for _ in range(n)],
        'Vehicle_Age': [random.randint(1, 10) for _ in range(n)],
        'Fuel_Type': [random.choice(['Diesel', 'Petrol', 'Electric']) for _ in range(n)],
        'Transmission_Type': [random.choice(['Automatic', 'Manual']) for _ in range(n)],
        'Engine_Size': [random.choice([800, 1000, 1500, 2000, 2500]) for _ in range(n)],
        'Odometer_Reading': [random.randint(1000, 150000) for _ in range(n)],
        'Last_Service_Date': [(datetime.datetime.now() - datetime.timedelta(days=random.randint(30, 365))).strftime('%Y-%m-%d') for _ in range(n)],
        'Warranty_Expiry_Date': [(datetime.datetime.now() + datetime.timedelta(days=random.randint(30, 365*2))).strftime('%Y-%m-%d') for _ in range(n)],
        'Owner_Type': [random.choice(['First', 'Second', 'Third']) for _ in range(n)],
        'Insurance_Premium': [random.randint(5000, 30000) for _ in range(n)],
        'Service_History': [random.randint(1, 10) for _ in range(n)],
        'Accident_History': [random.randint(0, 3) for _ in range(n)],
        'Fuel_Efficiency': [random.uniform(10, 20) for _ in range(n)],
        'Tire_Condition': [random.choice(['New', 'Good', 'Worn Out']) for _ in range(n)],
        'Brake_Condition': [random.choice(['New', 'Good', 'Worn Out']) for _ in range(n)],
        'Battery_Status': [random.choice(['New', 'Good', 'Weak']) for _ in range(n)],
        'Owner_Name': [fake.name() for _ in range(n)],
        'Owner_Address': [fake.address() for _ in range(n)],
        'License_Plate': [fake.license_plate() for _ in range(n)],
        'VIN_Number': [fake.ean(length=13) for _ in range(n)],  # Corrected length to 13
        'Purchase_Date': [fake.date_between(start_date='-10y', end_date='today').strftime('%Y-%m-%d') for _ in range(n)],
        'Purchase_Price': [random.randint(5000, 50000) for _ in range(n)],
        'Registration_Date': [fake.date_between(start_date='-10y', end_date='today').strftime('%Y-%m-%d') for _ in range(n)],
        'Insurance_Expiry_Date': [(datetime.datetime.now() + datetime.timedelta(days=random.randint(30, 365*2))).strftime('%Y-%m-%d') for _ in range(n)],
        'Color': [fake.color_name() for _ in range(n)],
        'Model_Year': [fake.year() for _ in range(n)],
        'Need_Maintenance': [random.randint(0, 1) for _ in range(n)]
    }
    return data

# Generate synthetic data
n = 50000
data = generate_data_with_faker(n)

# Convert the dictionary to a DataFrame
df = pd.DataFrame(data)

# Save the DataFrame to a CSV file
df.to_csv('vehicle_maintenance_data_faker.csv', index=False)

# Display the DataFrame
print(df.head())

  Vehicle_Model  Mileage Maintenance_History  Reported_Issues  Vehicle_Age  \
0    Motorcycle    33129                Poor                1            8
1    Motorcycle    69860             Average                2            6
2           Bus    48888                Poor                0            3
3           Van    68415             Average                0            1
4           SUV    37018                Good                4           10

  Fuel_Type Transmission_Type  Engine_Size  Odometer_Reading  \
0  Electric            Manual         1000             18246
1    Petrol            Manual          800             30681
2    Petrol         Automatic          800             18065
3    Diesel         Automatic          800             53794
4    Diesel         Automatic         2000            100923

  Last_Service_Date  ...                                      Owner_Address  \
0        2023-04-05  ...  46310 Andersen Brook Suite 172\nSouth Alexabur...
1        2024-01-31  ...      6964 Stephens Overpass\nEast Ashley, PW 69949
2        2024-01-21  ...            99251 Jones Ports\nCynthiaton, MH 16792
3        2023-08-12  ...             55946 Kari Shoal\nDavidhaven, WY 99594
4        2023-09-22  ...   8720 Gill Ranch Suite 399\nKimberlyton, NM 77987

  License_Plate     VIN_Number  Purchase_Date  Purchase_Price  \
0       KEJ 501  7837703467907     2023-12-07            7766
1      SB 63420  7911188875270     2017-03-30           21807
2       8-W8686  6402690200649     2018-01-11           44341
3       LWI 247  6637915422128     2015-05-10           19149
4       HAH 785  9186120928798     2018-12-14           12477

   Registration_Date Insurance_Expiry_Date           Color Model_Year  \
0         2021-07-03            2024-05-12       GoldenRod       2013
1         2019-07-24            2024-06-14  CornflowerBlue       2002
2         2019-03-13            2026-03-08  LightSteelBlue       1999
3         2022-12-03            2024-05-18          Indigo       2009
4         2015-10-14            2025-09-06       SlateBlue       1981

  Need_Maintenance
0                1
1                0
2                1
3                1
4                1

[5 rows x 30 columns]

In [10]:
df_fake = pd.read_csv('vehicle_maintenance_data_faker.csv')
df_fake

,Vehicle_Model,Mileage,Maintenance_History,Reported_Issues,Vehicle_Age,Fuel_Type,Transmission_Type,Engine_Size,Odometer_Reading,Last_Service_Date,...,Owner_Address,License_Plate,VIN_Number,Purchase_Date,Purchase_Price,Registration_Date,Insurance_Expiry_Date,Color,Model_Year,Need_Maintenance
0,Motorcycle,33129,Poor,1,8,Electric,Manual,1000,18246,2023-04-05,...,46310 Andersen Brook Suite 172\nSouth Alexabur...,KEJ 501,7837703467907,2023-12-07,7766,2021-07-03,2024-05-12,GoldenRod,2013,1
1,Motorcycle,69860,Average,2,6,Petrol,Manual,800,30681,2024-01-31,...,"6964 Stephens Overpass\nEast Ashley, PW 69949",SB 63420,7911188875270,2017-03-30,21807,2019-07-24,2024-06-14,CornflowerBlue,2002,0
2,Bus,48888,Poor,0,3,Petrol,Automatic,800,18065,2024-01-21,...,"99251 Jones Ports\nCynthiaton, MH 16792",8-W8686,6402690200649,2018-01-11,44341,2019-03-13,2026-03-08,LightSteelBlue,1999,1
3,Van,68415,Average,0,1,Diesel,Automatic,800,53794,2023-08-12,...,"55946 Kari Shoal\nDavidhaven, WY 99594",LWI 247,6637915422128,2015-05-10,19149,2022-12-03,2024-05-18,Indigo,2009,1
4,SUV,37018,Good,4,10,Diesel,Automatic,2000,100923,2023-09-22,...,"8720 Gill Ranch Suite 399\nKimberlyton, NM 77987",HAH 785,9186120928798,2018-12-14,12477,2015-10-14,2025-09-06,SlateBlue,1981,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,SUV,45889,Good,1,3,Diesel,Automatic,2500,94019,2023-12-09,...,"54198 Anna Club Apt. 833\nChristianmouth, FL 3...",293-HAJ,5088496047841,2020-12-24,35961,2019-02-17,2024-06-17,Wheat,1994,0
49996,SUV,50943,Poor,5,8,Petrol,Manual,1500,5751,2023-06-27,...,"302 Sarah Drives Apt. 872\nMichaelbury, AR 78098",HJR 852,4635567821636,2023-04-08,10060,2023-10-29,2024-11-18,LemonChiffon,1983,1
49997,Motorcycle,70251,Average,1,7,Electric,Automatic,2500,64069,2024-02-23,...,"37466 Cain Fall\nFrazierside, OK 32027",01V U57,7331944428906,2016-06-09,25270,2015-02-14,2026-02-21,Tomato,2022,0
49998,Van,79023,Poor,3,4,Petrol,Manual,1500,78546,2023-06-24,...,"8410 Sarah Curve\nJoyceside, GA 83949",3VJ0625,3272617869692,2014-04-10,10882,2019-05-05,2025-08-21,Red,1977,1
49999,Truck,46442,Good,5,7,Petrol,Manual,2500,24649,2023-04-06,...,"097 Tiffany Causeway\nEast Shannonview, MO 55719",5Y KM322,2898129619801,2020-06-11,5962,2017-06-09,2025-03-25,LightGray,2007,1